<template>
  <div>
    <h2>Privacy Policy</h2>
    <h3>隐私政策</h3>
    <div>
      Updated Date: [ Janueary 1], 2021<br>
      更新日期：2021年[ 1 ]月[ 1 ]日<br>
      <br>

      Introduction<br>
      概要<br>
      <br>
      [Yue Ye Network Technology Co.,Ltd] (also referred to as “Yue Ye,” “Company,” “we,” “us,” or “our”) respects the privacy and personal information of our users (“user” or “you”). This privacy policy (the “Policy”) explains how we collect, use, disclose, and safeguard your information when you visit our mobile application (the “Application”, including but not limited to any mobile applications or mini programs that hyperlink to this Policy and are available for download in the Apple App Store, Google Play Store or any other third party app store, or are pre-installed on third party devices or other platform), , along with the rights you are entitled to. We will use this Policy to explain the relevant details, including the following:
      <br>[悦夜网络科技有限公司]（也称为“悦夜”、“公司”、“我们”或“我们的”）尊重我们用户（“用户”或“您”）的隐私和个人信息。本隐私政策(以下简称“政策”)解释了当您访问我们的移动应用程序（“应用”，包括但不限于指向本政策的任何可在苹果应用商店、谷歌应用商店或任何其他第三方应用商店下载，或预装在第三方设备或其他平台上的移动应用程序或小程序）时，我们如何收集、使用、披露和保护您的信息，以及您有权享有的权利。我们将通过本政策向您阐述相关事宜，其中要点如下：
      <br>
      <br>-	By accessing, visiting or using our Application, you warrant and represent that you have read, understood and agreed to this Policy. If you disagree with anything in this Policy, you must not use or access the Application.
      <br>通过进入、访问或使用我们的应用，您保证并声明您已阅读、理解并同意本政策。如果您不同意本政策中的任何内容，您不得使用或访问本应用。
      <br>
      <br>-	Whilst using some features, we will collect your personal sensitive information after obtaining your consent. Unless it is required by the relevant laws and regulations for you to provide such information, refusing to provide such information will only result in your not being able to use the specific functions relating to such information, but does not affect your normal use of other functions of Application.
      <br>当您使用一些功能时，我们会在获得您的同意后，收集您的个人敏感信息。除非按照相关法律法规要求必须收集，拒绝提供这些信息仅会使您无法使用相关特定功能，但不影响您正常使用应用的其他功能。
      <br>
      <br>-	We may periodically make changes to this Policy as we update or expand our Application. We will notify you of any material changes to this Policy by [notifying you via the email we have on file for you, or by] means of a notice on our Application in advance of the effective date of the changes. If you do not agree to the changes, you should discontinue your use of the Application prior to the time the modified Policy takes effect. If you continue using the Application after the modified Policy takes effect, you will be bound by the modified Policy.
      <br>当我们更新或扩展我们的应用时，我们可能会定期更改本政策。对于本政策的任何重大更改，我们将[通过我们为您存档的电子邮件通知您，或]在更改生效日期之前通过我们的应用通知您。如果您不同意这些更改，您应该在修改后的政策生效之前停止使用本应用。如果您在修改后的政策生效后继续使用本应用，您将受到修改后的政策的约束。
      <br>
      <br>-	You can access, correct and delete your personal information through the instructions listed in this Policy, or you can withdraw your consent, cancel your account, report complaints and manage your privacy settings.
      <br>您可以通过本政策所列途径访问、更正、删除您的个人信息，也可以撤回同意、注销账号、投诉举报以及管理您的隐私设置。
      <br>
      <br>For more detailed information on the above, please refer to the relevant sections in following index:
      <br>如您想了解更加详尽的信息，请根据以下索引阅读相应章节：
      <br>
      <br>1.	The Information We Collect
      <br>我们收集的信息
      <br>
      <br>2.	How We Use Information
      <br>我们如何使用信息
      <br>
      <br>3.	The Location and Time Period of Storing Information
      <br>存储信息的地点和期限
      <br>
      <br>4.	Information Security
      <br>信息安全
      <br>
      <br>5.	Protection of Minors
      <br>未成年人保护
      <br>
      <br>6.	Transfer of Data to Third Parties
      <br>对外提供
      <br>
      <br>7.	Your Rights
      <br>您的权利
      <br>
      <br>8.	Amendments
      <br>变更
      <br>
      <br>9.	Others
      <br>其他
      <br>
      <br>10.	Contact Us
      <br>联系我们
      <br>
      <br>1.	The Information We Collect
      <br>我们收集的信息

      <br>In the process of using the Application, we will, in accordance with the following ways, collect information provided by you during the use of the Application or information generated by the use of the Application, in order to provide service to you, to optimize our service and protect your account security:
      <br>在您使用应用的过程中，我们会按照如下方式收集您在使用应用时主动提供或因为使用应用而产生的信息，用以向您提供服务、优化我们的服务以及保障您的账号安全：
      <br>
      <br>1.1.	Registration information. When you register with Application, we will collect your Wechat IP, Nickname, Profile Picture, Phone Number, City location, Gender, etc.  and store basic information (name, address, Legal representative information and bank account, etc.)in order to assist you with completing Application registration and to protect your Application account security.
      <br>注册信息。当您注册应用时，我们会收集您的微信IP、微信昵称、头像、手机号码、、城市位置、性别等基本信息 以及门店基本信息（名称、地址、法人身份信息、银行账户等），收集这些信息是为了帮助您完成注册，保护您应用账号的安全。
      <br>
      <br>1.2.	Device and Log Information. When you use the Application, in order to ensure the normal use of our Application, to maintain the normal operation of our Application, and to optimize and improve our service and protect the safety of your account, we will collect information about your device model, operating system, unique device identifier, login IP address, Application version number, access network mode , type and status, the quality of your network, equipment accelerators (such as gravity sensing equipment), operation logs, service logs (such as the information you search or browse on Application, or the information about service failure, referrer URLs etc.) and other log information. Such information is required to provide you with service and are basic information which must be collected, and such separate device and log information cannot identify a specific natural person.
      <br>设备和日志信息。当您使用应用时，为保障您正常使用我们的应用，维护我们应用的正常运行，优化及改进我们的服务，向您提供更契合您需求的页面展示和搜索结果，以及保障您的账号安全，我们可能会收集您的设备信息及服务日志信息，包括：[设备型号、操作系统、唯一设备标识符、登陆IP地址、应用软件版本号、接入网络的方式、类型和状态、网络质量数据、设备加速器（如重力感应设备）、操作日志、服务日志信息（如您在应用搜索、查看的信息、服务故障信息、引荐网址等信息）]等日志信息。这类信息是为提供服务必须收集的基础信息，且单独的设备信息、服务日志是无法识别特定自然人身份的信息。
      <br>
      <br>1.3.	Location Information. We will obtain your independently consent prior to recording your location information, for the purpose of providing you with specific service. Such information is sensitive information, refusing to provide such information may only result in you being unable to use certain functions, but does not affect your normal use of Application’s other functions.
      <br>位置信息。我们会在获得您的自主选择同意后，记录您的地理位置信息，目的是为了向您提供特定服务。该信息属于敏感信息，拒绝提供该信息仅会使您无法使用特定功能，但不影响您正常使用应用的其他功能。
      <br>
      <br>1.4.	Order Management information. When you use the Application to order specific goods or services, you need to provide at least your consignee ’s name, address, and contact phone number. At the same time, the order will contain the information of the goods or services you purchased, order number, and order creation time, payment amount. Such information is collected to help you successfully complete the transaction, protect the transaction security, query order information, provide customer service and after-sales, and other purposes that we clearly informed.
      <br>订单管理信息。当您使用应用中订购具体商品或服务时，你需要至少提供您的收货人姓名，地址，联系电话，同时该订单中会载明您所购买的商品或服务信息，订单号，订单创建时间，支付金额。收集这些信息是为了帮助您顺利完成交易、保障交易安全、查询订单信息、提供客服与售后及其他我们明确告知的目的。
      <br>
      <br>1.5.	After you place an order, you can choose the payment services provided by the third-party payment institutions (WeChat Pay, UnionPay, etc.) that Yueye cooperates with. The payment function itself does not collect your personal information, but we need to share your order number and transaction amount information with these payment institutions to confirm your payment instructions and complete the payment.
      <br>在您下单后，您可以选择悦夜合作的第三方支付机构（微信支付、银联等通道）所提供的支付服务。支付功能本身并不收集您的个人信息，但我们需要将您的订单号及交易金额信息与这些支付机构共享以实现其确认您的支付指令并完成支付。
      <br>
      <br>1.6.	When you use Application’s [ Comment / Q&A ] function, your uploaded photos, comments, likes，and other information will be stored in our server, because the storage of such information is necessary for this function to work. We will store such information in an encrypted manner, and you may delete it at any time. We will not provide the above contents to any third party or use it for purposes other than implementing this function, unless you elect to do so or unless we are required to follow relevant laws and regulations.
      <br>当您使用应用 [评论或问答] 功能时，您上传的文字、照片、视频、评论、点赞等信息会存储在我们的服务器中，因为存储是实现这一功能所必需的。我们会以加密的方式存储，您也可以随时删除这些信息。除非经您自主选择或遵从相关法律法规要求，我们不会对外提供上述信息，或者将其用于该功能以外的其他用途。
      <br>
      <br>1.7.	Third-party Service Information. The third-party service in the Application is provided by external third-party entities, and the Application cannot obtain the information generated by you when using such third-party service. However, if you have expressly agreed for the third party to obtain your information, the third party will obtain your information through Application’s programming interface. Refusing to provide such information may result in you being unable to use the above third-party service, but does not affect your normal use of Application’s other functions.
      <br>第三方服务信息。应用服务中的第三方服务由外部第三方主体提供，应用无法获得您在使用该类第三方服务时产生的信息。但是，如果您已明示同意该第三方获得您的信息，该第三方将通过应用接口获得您的信息。拒绝提供该信息仅会使您无法使用上述第三方服务，但不影响您正常使用应用的功能。
      <br>
      <br>1.8.	When you use the Application with other interoperable software or hardware, providers of such software or hardware can, with your consent, obtain relevant information that you actively disclose or transmit on the Application. You should fully understand product features and information protection policy of other software or hardware before granting your consent.
      <br>当您使用应用与其他软件或硬件互通功能时，其他软件或硬件的提供方在经您同意后可以获取您在应用主动公开或传输的相关信息，您在选择前应充分了解其他软件或硬件的产品功能及信息保护策略。
      <br>
      <br>In addition, in accordance with relevant laws and regulations and national standards, in the following circumstances, we may collect and process your relevant personal information without asking for your consent:
      <br>另外，根据相关法律法规及国家标准，以下情形中，我们可能会收集、使用您的相关个人信息无需征求您的授权同意：
      <br>
      <br>1)	When it is directly related to national interests such as national security and national defense, or it is directly related to major public interests such as public safety, public health, and public knowledge;
      <br>与国家安全、国防安全等国家利益直接相关的，与公共安全、公共卫生、公众知情等重大公共利益直接相关的；
      <br>
      <br>2)	When it is directly related to a criminal investigation, prosecution, trial or execution of judgments;
      <br>与犯罪侦查、起诉、审判和判决执行等直接相关的；
      <br>
      <br>3)	In order to protect vital legitimate interests of you or of other individuals, such as right of life, property, and reputation, while it’s hardly to obtain the consent of the individual;
      <br>出于维护您或其他个人的生命、财产、声誉等重大合法权益但又很难得到本人同意的；
      <br>
      <br>4)	When the personal information is disclosed to the public by yourself;
      <br>所收集的个人信息是您自行向社会公众公开的；
      <br>
      <br>5)	When the personal information is collected from legally publicly disclosed information, such as legitimate news reports, government information disclosure, etc.;
      <br>从合法公开披露的信息中收集个人信息的，如合法的新闻报道、政府信息公开等渠道；
      <br>
      <br>6)	When it is necessary for entering into and/or performance of a contract to which you are the party;
      <br>根据您要求签订和履行合同所必需的；
      <br>
      <br>7)	When it is necessary for maintenance of the safe and stable operation of the products or service provided, such as discovering malfunctions and/or troubleshooting products or service;
      <br>用于维护所提供的产品或服务的安全稳定运行所必需的，例如发现、处置产品或服务的故障；
      <br>
      <br>8)	When it is necessary for legitimate news reporting;
      <br>为开展合法的新闻报道所必需的；
      <br>
      <br>9)	When it is necessary for conducting statistical or academic research which is for public interest, and when the results of academic research or description are provided externally, the personal information contained is de-identified;
      <br>出于公共利益开展统计或学术研究所必要，且其对外提供学术研究或描述的结果时，对结果中所包含的个人信息进行去标识化处理的；
      <br>
      <br>10)	Other circumstances as stipulated by laws and regulations.
      <br>法律法规规定的其他情形。
      <br>
      <br>Please note that at present, the Application will not actively obtain your personal information from a third party outside of Yue Ye. In the event that we need to obtain your personal information indirectly from a third party for future business developments, we will inform the source, type and scope of the use of your personal information to you prior to obtaining such information. For example, where the Application requires to process personal information for a specific development which is beyond the scope of what you originally agreed to provide to a third party, we will obtain your prior express consent before processing your personal information; In addition, we will strictly abide by the relevant laws and regulations, and require that third parties guarantee the legitimacy of the information provided.
      <br>请您注意，目前应用不会主动从悦夜以外的第三方获取您的个人信息。如未来为业务发展需要从第三方间接获取您个人信息，我们会在获取前向您明示您个人信息的来源、类型及使用范围，如应用开展业务需进行的个人信息处理活动超出您原本向第三方提供个人信息时的授权同意范围，我们将在处理您的该等个人信息前，征得您的明示同意；此外，我们也将会严格遵守相关法律法规的规定，并要求第三方保障其提供的信息的合法性。
      <br>
      <br>2.	How We Use Information
      <br>我们如何使用信息
      <br>
      <br>We will transfer your store basic data to third parties service providers to verify authenticity of the POC. Where data is transferred to our service providers, this is done only in a data-protected way, and only when doing so is necessary to provide our services.
      <br>我们会将您的门店基本信息传输给第三方服务商，以做售点真实性验证。当数据被传输至第三方服务商时，数据将只会以受保护的形式被传输，并且仅在提供我们的服务所必需时才会被传输。
      <br>
      <br>We only share your personal information and store basic information with our third-parties service providers (Distributors). However, we will only share necessary order information and are bound by the stated purpose in this privacy policy. If our third-parties service providers want to change the purpose of processing personal information, they will again seek your authorization and consent.
      <br>我们仅会将您的个人信息和售点基本信息与我们的三方服务提供方（经销商）共享，仅用作帮助完成订单的目的。但我们只会共享必要的订单信息，且受本隐私政策中所声明目的的约束。我们的三方服务方如要改变其中的个人信息的处理目的，将再次征求您的授权同意。
      <br>
      <br>We may use information collected by certain features for our other services. For example, we may use the information we collect when you use one of our features, and provide you with specific content in another service, including, but not limited to ads, information security tips for content you have read, indirect crowd portraits based on feature tags, and providing more accurate and personalized services and content. The information generated about your use of this application will not be disclosed to third parties.
      <br>我们可能将通过某些功能所收集的信息用于我们的其他服务。例如，我们可能将您在使用我们某一功能或服务时我们收集的信息，在另一功能或服务中用于向您提供特定内容，包括但不限于展示广告、对您阅读过的内容进行信息安全类提示、基于特征标签进行间接人群画像并提供更加精准和个性化的服务和内容等。关于您对本网站的使用情况将不会泄露给任何第三方。
      <br>
      <br>In order to ensure the security of our Application, and to enable us to better understand the operations of our applications, we may record information such as your frequency of using our Application, crash logs, overall usage, performance data, and the sources that the Application is installed from.
      <br>为了确保应用的安全，帮助我们更好地了解我们应用的运行情况，我们可能记录相关信息，例如，您使用应用的频率、崩溃数据、总体使用情况、性能数据以及应用的来源。
      <br>
      <br>Where we utilize your personal information beyond the scope of our collection statement or a direct or reasonable connection, we will inform you and obtain your prior express consent again before using your personal information in such situations.
      <br>如我们使用您的个人信息，超出了与收集时所声称的目的及具有直接或合理关联的范围，我们将在使用您的个人信息前，再次向您告知并征得您的明示同意。
      <br>
      <br>3.	The Location and Time Period of Storing Information
      <br>存储信息的地点和期限
      <br>
      <br>We will store user’s personal information collected within mainland China within the territory in accordance with applicable laws and regulations. In general, we will retain your personal information in the shortest possible time to fulfill the purpose of collection of such information. However, for the following purposes, we may change the retention period for the purposes of compliance:
      <br>我们会按照法律法规规定，将境内收集的用户个人信息存储于中国大陆境内。一般而言，我们仅为实现目的所必需的时间保留您的个人信息。但在下列情况下，我们有可能因需符合法律要求，更改个人信息的存储期限：
      <br>
      <br>•	To comply with the relevant laws and regulations;
      <br>为遵守适用的法律法规等有关规定；
      <br>
      <br>•	To comply with court decisions, rulings or requirements of other legal procedures;
      <br>为遵守法院判决、裁定或其他法律程序的规定；
      <br>
      <br>•	To comply with the requirements of relevant government agencies or other legally authoritative entities;
      <br>为遵守相关政府机关或法定授权组织的要求；
      <br>
      <br>•	We have reasons to believe that we need to comply with applicable laws and regulations;
      <br>我们有理由确信需要遵守法律法规等有关规定；
      <br>
      <br>•	Reasonable and necessary purposes to implement relevant service agreements or this Policy, or to protect public interest and to protect personal safety and property and other legitimate rights and interests of our clients, ourselves, our affiliates, our users or employees.
      <br>为执行相关服务协议或本政策、维护社会公共利益，为保护们的客户、我们或我们的关联公司、其他用户或雇员的人身财产安全或其他合法权益所合理必需的用途。
      <br>
      <br>Should the operation of our products or service terminate, we will inform you in the form of push notifications, announcements, etc., and delete or anonymize your personal information within a reasonable period of time.
      <br>当我们的产品或服务发生停止运营的情形时，我们将以推送通知、公告等形式通知您，并在合理的期限内删除您的个人信息或进行匿名化处理。
      <br>
      <br>4.	Information Security
      <br>信息安全
      <br>
      <br>We strive to secure users' information to prevent information leakage, improper use, unauthorized access or disclosure.
      <br>我们努力为用户的信息安全提供保障，以防止信息的丢失、不当使用、未经授权访问或披露。
      <br>
      <br>We will use a variety of security measures to ensure the security of information within reasonable security standards. For example, we will use encryption technology (for example, SSL) and other means to protect your personal information.
      <br>我们将在合理的安全水平内使用各种安全保护措施以保障信息的安全。例如，我们会使用加密技术（例如，SSL）等手段来保护您的个人信息。
      <br>
      <br>We use ever-improving technical means to enhance the security of the software installed on your device to prevent your personal information from leaking. For example, we may perform partial information encryption on your device for secure transmission; to prevent viruses, Trojans or other malicious programs or website, we may collect the information about applications installed on your device or process information regarding the running application.
      <br>我们通过不断提升的技术手段加强安装在您设备端的软件的安全能力，以防止您的个人信息泄露。例如，我们为了安全传输可能会在您设备本地完成部分信息加密的工作；为了预防病毒、木马程序或其他恶意程序、网站，我们可能会收集您设备安装的应用信息或正在运行的进程信息。
      <br>
      <br>We have set up specialized management systems, processes and organizations to ensure the security of information. For example, we strictly limit the range of people who may access such information and require them to comply with the confidentiality obligations and conduct supervision.
      <br>我们建立专门的管理制度、流程和组织以保障信息的安全。例如，我们严格限制访问信息的人员范围，要求他们遵守保密义务，并进行监督。
      <br>
      <br>In the case of information leakage or other incidents involving information security, we will initiate contingency plans to prevent the wide spread of security incidents.
      <br>若发生个人信息泄露等安全事件，我们会启动应急预案，阻止安全事件扩大。
      <br>
      <br>5.	Protection of Minors
      <br>未成年人保护
      <br>
      <br>This Application is not intended for people under legal drink age (juveniles who under 18 years old are forbidden to drink alcohol under Chinese law). Therefore, when you visit our Application, please confirm you are at least 18 years old. Meanwhile, we will perform age checks upon visiting the Application. If we later learn that a minor has provided us with personal information, we will delete it.
      <br>本应用不适用于不满法定饮酒年龄的人（在中国指未满18周岁的未成年人）。因此，在访问应用时，请确保您已年满 18 周岁。同时，我们在您访问应用时会进行年龄检查。如果我们事后得知未成年人为我们提供了个人信息，我们将删除该等信息。
      <br>
      <br>6.	Transfer of Data to Third Parties
      <br>对外转让
      <br>
      <br>We will not publicly disclose personal information collected by us. If we have to disclose such information publicly, we will inform you of the purpose of such disclosure, type of information disclosed and the sensitive information that may be involved, and obtain your prior express consent.
      <br>我们不会对外公开披露收集的个人信息，如必须公开披露时，我们会向您告知此次公开披露的目的、披露信息的类型及可能涉及的敏感信息，并征得您的明示同意。
      <br>
      <br>As our business continues to develop, we may engage in mergers, acquisitions, transfers of assets, etc. We will continue to protect your personal information and require new controllers to continue to protect your personal information in accordance with the laws and regulations and the standards as strict as required by this Policy and inform you of related information.
      <br>随着我们业务的持续发展，我们有可能进行合并、收购、资产转让等交易，我们将按照法律法规及不低于本政策所要求的标准继续保护或要求新的控制者继续保护您的个人信息，并通知您相关信息。
      <br>
      <br>In addition, in accordance with relevant laws and regulations and national standards, in the following circumstances, we may share, transfer, or publicly disclose personal information without prior consent of the subject of personal information:
      <br>另外，根据相关法律法规及国家标准，以下情形中，我们可能会共享、转让、公开披露个人信息无需事先征得个人信息主体的授权同意：
      <br>
      <br>•	When it is directly related to national security or national defense;
      <br>与国家安全、国防安全直接相关的；
      <br>
      <br>•	When it is directly related to public safety, public health, or major public interests;
      <br>与公共安全、公共卫生、重大公共利益直接相关的；
      <br>
      <br>•	When it is directly related to a criminal investigation, prosecution, trial or execution of judgments;
      <br>与犯罪侦查、起诉、审判和判决执行等直接相关的；
      <br>
      <br>•	When it is for protecting vital legitimate interests of you or of other individuals, such as right of life, property, and reputation, while it’s hardly to obtain the consent of the individual;
      <br>出于维护个人信息主体或其他个人的生命、财产等重大合法权益但又很难得到本人同意的；
      <br>
      <br>•	When the personal information is disclosed to the public by yourself;
      <br>个人信息主体自行向社会公众公开的个人信息；
      <br>
      <br>•	When the personal information is collected from legally publicly disclosed information, such as legitimate news reports, government information disclosure, etc.
      <br>从合法公开披露的信息中收集个人信息的，如合法的新闻报道、政府信息公开等渠道。
      <br>
      <br>7.	Your Rights
      <br>您的权利
      <br>
      <br>During your course of using this Application, in order to provide you with an easier way to access, change, delete your personal information while ensuring you with the right to withdraw your consent regarding the use of personal information and the right to cancel your account, we have provided you with the applicable function when designing the product. You may refer to the following operational Policy as linked. In addition, we have also set up a report and complaints channel (please contact TBD), in order to address your feedback in a timely manner.
      <br>在您使用应用期间，为了您可以更加便捷地访问、更正、删除您的个人信息，同时保障您撤回对个人信息使用的同意及注销账号的权利，我们在产品设计中为您提供了相应的操作设置，您可以参考下面链接的政策进行操作。此外，我们还设置了投诉举报渠道(请联系TBD)，您的意见将会得到及时的处理。
      <br>
      <br>8.	Amendments
      <br>变更
      <br>
      <br>We may revise this Policy in due course. In the event where the terms of this Policy are amended, we will show you amended Policy by way of push notifications and/or pop-up windows when you log in or when the application version has been updated. Please note that we will follow the updated Policy to collect, use and store your personal information only after you have tapped on the consent button in the pop-up window.
      <br>我们可能会适时对本政策进行修订。当政策的条款发生变更时，我们会在您登录及版本更新时以推送通知、弹窗的形式向您展示变更后的政策。请您注意，只有在您点击弹窗中的同意按钮后，我们才会按照更新后的政策收集、使用、存储您的个人信息。
      <br>
      <br>9.	Others
      <br>其他
      <br>
      <br>This Application is hosted in the People’s Republic of China(“PRC”). If you are attempting to access this Application from a physical location within the United States, Europe, or any other region with laws or regulations governing personal data collection, use, and disclosure that differ from the PRC laws, please be advised that your use of this Application is governed by the PRC laws and this Policy. To the extent you provide personal data through the Application, you are transferring your data to the PRC.
      <br>本应用的主机位于中华人民共和国（“中国”）。如果您在尝试访问应用时位于美国、欧洲或其他存在与中国法关于个人信息收集、使用和披露的规定不同的法律法规的地区，请注意您对本应用的使用将受中国法律以及本政策的管辖。您通过本应用提供个人信息数据时，您的数据将会被传输至中国。
      <br>
      <br>10.	Contact Us
      <br>
      <br>If you have any other complaints, suggestions, or queries regarding personal information of minors, please send your queries to or to the following address:
      <br>当您有其他的投诉、建议、未成年人个人信息相关问题时，可以将您的问题发送至或寄到如下地址：
      <br>
      <br>[Address:  Room B910-35, No.666 Beijing East Road, Huangpu District, Shanghai]
      <br>[地址：上海市黄浦区北京东路666号裙楼B910-35室]
      <br>
      <br>[Yue Ye business entity name: Yue Ye Network Technology Co.,Ltd Co.,Ltd]
      <br>[悦夜实体名称：悦夜网络科技有限公司]
      <br>
      <br>[Name of person in charge：Rongren Wang]
      <br>[负责人姓名 王仁荣]
      <br>
      <br>[Postcode：200001]
      <br>
      <br>[邮编：200001]
      <br>
      <br>You can contact us by writing your queries, feedback and request for data. We may collect your name, e-mail address and your request details. Only mandatory details are your email address and request details, other details are optional to share with us. Your personal details will be saved only so that we can respond to your request, and will subsequently be deleted, unless there are legal requirements stipulating the retention of this data. We will review your queries as soon as possible and respond within [ thirty ] days after verifying your identity.
      <br>您可以通过填写问题、反馈和数据请求与我们联系。我们可以收集您的姓名、电子邮件地址和您的请求详情。只有您的电子邮件地址和请求详情是强制要求提供的信息，对于其他详情资料您可以选择是否与我们分享。您的个人资料将仅用于我们回复您的请求而被保存，除非有法律规定要求保留，否则该等数据随后将被删除。我们将尽快审核所涉问题，并在验证您的用户身份后的[ 30 ]天内予以回复。
    </div>
  </div>
</template>
